# docker-compose.yml

version: '2'

services:
    php: #php-fpm container
        image: jvancoillie/php-fpm-symfony 
        ports:
            - 9000:9000
        links:
            - db:mysqldb
            - redis
        volumes:
            - ${SYMFONY_PROJECT_PATH}:/var/www/html/symfony #replace $SYMFONY_PROJECT_PATH in .env file 
            - ./logs/symfony:/var/www/html/symfony/var/logs
    db: #mysql container
        image: mysql
        volumes:
            - ./data/db:/var/lib/mysql #mysql data 
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}        
    redis: # redis container
        image: redis:alpine
        ports:
            - 6379:6379

    nginx: #nginx container
        image: jvancoillie/nginx-symfony
        ports:
            - 80:80
        environment: #need for nginx server config
            - FPM_HOST=phpfpmhost      
            - FPM_PORT=9000
            - PROJECT_NAME=symfony      
        links:
            - php:phpfpmhost
        volumes_from:
            - php:ro
        volumes:
            - ./logs/nginx/:/var/log/nginx

## comment the following lines if u dont want to use ELK
    kibana:
      image: kibana:latest
      ports:
        - 5601:5601
      volumes:
        - ./config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      networks:
        - docker_elk

    elasticsearch:
      image: elasticsearch:latest
      container_name: elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      mem_limit: 1g
      cap_add:
        - IPC_LOCK
      volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
        - 9300:9300
      networks:
        - docker_elk

    logstash:
      image: logstash:latest
      command: -f /etc/logstash/conf.d/
      volumes_from:
        - php
        - nginx
      volumes:
        - ./config/logstash:/etc/logstash 
      ports:
        - 5000:5000
      networks:
        - docker_elk    

networks:
    docker_elk:
      driver: bridge
